import rawCore from './core-data';
import advancedHealth from './advanced-health-data';
import type { Category } from './site';

export type Input = { key: string; label: string; value: number | string; type?: 'number' | 'date'; step?: number; min?: number; max?: number; help?: string };
export type Tool = { category: Category; group?: string; slug: string; title: string; description: string; op: string; inputs: Input[]; formula: string; unit?: string; params: number[]; featured?: boolean; keywords: string[]; advanced?: boolean; sources?: { label: string; url: string }[] };

const core: Tool[] = rawCore.map((item: any) => ({
  category: item.c, slug: item.s, title: item.t, op: item.o,
  inputs: item.i.map((input: any[], index: number) => ({ key: `v${index}`, label: input[0], value: input[1], type: input[2] })),
  formula: item.f, unit: item.u, params: item.p, featured: item.x,
  description: `Calculate ${item.t.replace(' Calculator', '').toLowerCase()} instantly with a transparent formula and editable inputs.`,
  keywords: [item.t.toLowerCase(), item.c, 'free online calculator'],
}));

const advancedFinance: Record<string, Partial<Tool>> = {
  'roi-calculator': { op:'roiAdvanced', advanced:true, description:'Calculate standard ROI, gain or loss, and annualized ROI from initial cost, final value, and holding period.', inputs:[{key:'v0',label:'Initial investment cost',value:1000,type:'number',min:.01,help:'Total amount invested, including relevant upfront costs.'},{key:'v1',label:'Final value or return',value:1350,type:'number',min:0,help:'Ending value or total return received.'},{key:'v2',label:'Holding period (years)',value:1,type:'number',min:.01,max:100,step:.01,help:'Time held; used for annualized ROI only.'}], formula:'ROI = (final value − initial cost) ÷ initial cost × 100; annualized ROI = (final value ÷ cost)^(1 ÷ years) − 1', unit:'return on investment', params:[], keywords:['ROI calculator','return on investment calculator','annualized ROI calculator','investment gain calculator','marketing ROI calculator'] },
  'discount-calculator': { op:'discountAdvanced', advanced:true, description:'Calculate the sale price, savings amount, and final total after a percentage discount, with optional sales tax.', inputs:[{key:'v0',label:'Original price',value:100,type:'number',min:0.01,help:'Regular price before the discount.'},{key:'v1',label:'Discount rate (%)',value:20,type:'number',min:0,max:100,step:.01,help:'Percentage taken off the original price.'},{key:'v2',label:'Sales tax rate (%)',value:0,type:'number',min:0,max:50,step:.01,help:'Optional tax applied after the discount.'}], formula:'Discount savings = original price × discount rate; sale price = original price − savings; final total = sale price × (1 + tax rate)', unit:'sale price', params:[], keywords:['discount calculator','sale price calculator','percent off calculator','discount percentage calculator','after tax discount calculator','how to calculate a discount'] },
  'tip-calculator': { op:'tipAdvanced', advanced:true, description:'Calculate the tip, tax, total bill, and per-person share from a bill amount, tip rate, tax rate, and group size.', inputs:[{key:'v0',label:'Bill subtotal',value:80,type:'number',min:0.01,help:'Food and drinks before tax and tip.'},{key:'v1',label:'Tip rate (%)',value:18,type:'number',min:0,max:100,step:.01,help:'Tip percentage applied to the bill subtotal.'},{key:'v2',label:'Sales tax rate (%)',value:8,type:'number',min:0,max:50,step:.01,help:'Optional tax rate applied to the bill subtotal.'},{key:'v3',label:'People splitting the bill',value:2,type:'number',min:1,max:100,step:1,help:'Number of people sharing the final total.'}], formula:'Tip = subtotal × tip rate; tax = subtotal × tax rate; total = subtotal + tip + tax; per person = total ÷ people', unit:'total bill', params:[], keywords:['tip calculator','restaurant tip calculator','tip split calculator','bill splitter','18 percent tip calculator','how much should I tip'] },
  'mortgage-calculator': { op:'mortgageAdvanced', advanced:true, description:'Estimate the full monthly housing payment, principal and interest, property taxes, insurance, HOA, PMI, extra payments, payoff time and financing cost.', inputs:[{key:'v0',label:'Home price',value:450000,type:'number',min:1,help:'Purchase price before the down payment.'},{key:'v1',label:'Down payment',value:90000,type:'number',min:0,help:'Cash paid upfront; 20% may avoid PMI.'},{key:'v2',label:'Annual interest rate (%)',value:6.5,type:'number',min:0,max:100,step:.01,help:'Nominal annual mortgage rate.'},{key:'v3',label:'Loan term (years)',value:30,type:'number',min:1,max:50,help:'Scheduled repayment period.'},{key:'v4',label:'Annual property tax',value:5400,type:'number',min:0,help:'Estimated yearly property tax.'},{key:'v5',label:'Annual home insurance',value:1800,type:'number',min:0,help:'Estimated yearly homeowners insurance.'},{key:'v6',label:'Monthly HOA fees',value:0,type:'number',min:0,help:'Monthly association or maintenance dues.'},{key:'v7',label:'Annual PMI rate (%)',value:.6,type:'number',min:0,max:10,step:.01,help:'Opening PMI estimate when the down payment is below 20%.'},{key:'v8',label:'Extra monthly payment',value:0,type:'number',min:0,help:'Optional extra principal paid each month.'}], formula:'Total monthly = principal and interest + tax/12 + insurance/12 + HOA + estimated PMI + extra principal', unit:'per month', params:[], keywords:['mortgage payment calculator','mortgage with taxes and insurance','PMI calculator','mortgage payoff calculator'] },
  'loan-calculator': { op:'loanAdvanced', advanced:true, description:'Calculate scheduled payment, extra-payment payoff time, total interest, fees and total borrowing cost for an installment loan.', inputs:[{key:'v0',label:'Loan amount',value:25000,type:'number',min:1,help:'Amount borrowed before fees.'},{key:'v1',label:'Annual interest rate (%)',value:8.5,type:'number',min:0,max:100,step:.01,help:'Nominal annual interest rate.'},{key:'v2',label:'Loan term (years)',value:5,type:'number',min:.08,max:50,step:.01,help:'Scheduled repayment period.'},{key:'v3',label:'Upfront fee (%)',value:2,type:'number',min:0,max:100,step:.01,help:'Origination or arrangement fee as a share of principal.'},{key:'v4',label:'Extra monthly payment',value:50,type:'number',min:0,help:'Optional amount added to every scheduled payment.'}], formula:'Payment = P × r(1+r)ⁿ ÷ ((1+r)ⁿ−1); borrowing cost = modeled interest + upfront fee', unit:'per month', params:[], keywords:['loan payment calculator','loan payoff calculator','loan with extra payments','total loan cost'] },
  'compound-interest-calculator': { op:'compoundAdvanced', advanced:true, description:'Project future value from a starting balance, recurring monthly contributions, interest rate, time and compounding frequency.', inputs:[{key:'v0',label:'Starting principal',value:10000,type:'number',min:0,help:'Amount invested at the beginning.'},{key:'v1',label:'Monthly contribution',value:250,type:'number',min:0,help:'Deposit made at the end of each month.'},{key:'v2',label:'Annual return (%)',value:7,type:'number',min:-99,max:1000,step:.01,help:'Expected nominal annual return; not a guarantee.'},{key:'v3',label:'Years',value:10,type:'number',min:.08,max:100,step:.01,help:'Investment time horizon.'},{key:'v4',label:'Compounds per year',value:12,type:'number',min:1,max:365,help:'Use 1 yearly, 4 quarterly, 12 monthly or 365 daily.'}], formula:'Future value = principal growth + future value of end-of-month contributions using an equivalent monthly rate', unit:'', params:[], keywords:['compound interest calculator with contributions','investment growth calculator','future value calculator'] },
  'savings-goal-calculator': { op:'savingsGoalAdvanced', advanced:true, description:'Find the monthly contribution required to reach a goal after accounting for current savings, return, time and compounding frequency.', inputs:[{key:'v0',label:'Savings goal',value:50000,type:'number',min:1,help:'Target balance at the end of the plan.'},{key:'v1',label:'Current savings',value:5000,type:'number',min:0,help:'Balance already saved today.'},{key:'v2',label:'Annual return (%)',value:6,type:'number',min:-99,max:1000,step:.01,help:'Expected nominal annual return; not a guarantee.'},{key:'v3',label:'Years to goal',value:5,type:'number',min:.08,max:100,step:.01,help:'Time available to reach the target.'},{key:'v4',label:'Compounds per year',value:12,type:'number',min:1,max:365,help:'Use 1 yearly, 4 quarterly, 12 monthly or 365 daily.'}], formula:'Required monthly contribution = remaining future-value gap ÷ contribution accumulation factor', unit:'per month', params:[], keywords:['savings goal calculator','monthly savings calculator','how much to save each month'] },
};
const advancedConstructionBusiness: Record<string, Partial<Tool>> = {
  'concrete-calculator': { op:'concreteAdvanced', advanced:true, description:'Estimate slab concrete volume, waste-adjusted order quantity and material cost using imperial or metric dimensions.', inputs:[{key:'v0',label:'Length (ft)',value:10,type:'number',min:0,help:'Slab or pour length.'},{key:'v1',label:'Width (ft)',value:10,type:'number',min:0,help:'Slab or pour width.'},{key:'v2',label:'Depth (in)',value:4,type:'number',min:0.1,help:'Concrete thickness before waste.'},{key:'v3',label:'Waste allowance (%)',value:10,type:'number',min:0,max:30,step:.5,help:'Common planning allowance for spillage and site variation.'},{key:'v4',label:'Price per yd³',value:150,type:'number',min:0,help:'Supplier price for the selected volume unit.'}], formula:'Order volume = length × width × depth ÷ 12 ÷ 27 × (1 + waste allowance); cost = order volume × price', unit:'yd³', params:[], keywords:['concrete calculator','how much concrete do I need','concrete yard calculator','slab concrete calculator','concrete waste allowance'] },
};
for (const tool of core) { if (advancedFinance[tool.slug]) Object.assign(tool, advancedFinance[tool.slug]); if (advancedHealth[tool.slug]) Object.assign(tool, advancedHealth[tool.slug]); if (advancedConstructionBusiness[tool.slug]) Object.assign(tool, advancedConstructionBusiness[tool.slug]); }
const validatedRemaining: Record<string, Partial<Tool>> = {
  'paint-calculator': { inputs:[{key:'v0',label:'Wall area (ft²)',value:1200,type:'number',min:.01,step:.01,help:'Total paintable surface area after subtracting large openings.'},{key:'v1',label:'Coverage per gallon',value:350,type:'number',min:.01,step:.01,help:'Manufacturer coverage estimate for one coat.'}] },
  'cagr-calculator': { inputs:[{key:'v0',label:'Beginning value',value:10000,type:'number',min:.01,step:.01,help:'Positive starting value.'},{key:'v1',label:'Ending value',value:18000,type:'number',min:.01,step:.01,help:'Positive ending value.'},{key:'v2',label:'Years',value:5,type:'number',min:.01,max:100,step:.01,help:'Elapsed period in years.'}] },
  'customer-acquisition-cost-calculator': { inputs:[{key:'v0',label:'Marketing and sales spend',value:5000,type:'number',min:0,step:.01,help:'Total acquisition-related marketing and sales costs for the measurement period.'},{key:'v1',label:'New customers acquired',value:100,type:'number',min:1,step:1,help:'New customers acquired in the same period and under the same customer definition.'}] },
  'customer-lifetime-value-calculator': { inputs:[{key:'v0',label:'Average order value',value:50,type:'number',min:.01,step:.01,help:'Average revenue per customer order.'},{key:'v1',label:'Purchases per year',value:4,type:'number',min:.01,step:.01,help:'Average number of purchases per customer each year.'},{key:'v2',label:'Customer lifespan (years)',value:3,type:'number',min:.01,step:.01,help:'Average active relationship duration.'},{key:'v3',label:'Gross margin (%)',value:60,type:'number',min:0,max:100,step:.1,help:'Optional margin used to estimate profit-based CLV from revenue CLV.'}] },
  'conversion-rate-calculator': { inputs:[{key:'v0',label:'Conversions',value:125,type:'number',min:0,max:1000000,step:1,help:'Completed goal actions in the measurement period.'},{key:'v1',label:'Visitors',value:5000,type:'number',min:1,max:100000000,step:1,help:'Visitors eligible for the same goal during the same measurement period.'}] },
  'grade-percentage-calculator': { inputs:[{key:'v0',label:'Points earned',value:87,type:'number',min:0,max:1000000,step:.01,help:'Points earned before any curve or bonus.'},{key:'v1',label:'Points possible',value:100,type:'number',min:.01,max:1000000,step:.01,help:'Total points available for the test or assignment.'},{key:'v2',label:'Curve or bonus points',value:0,type:'number',min:0,max:1000000,step:.01,help:'Optional points added before converting to a percentage.'}] },
  'weighted-grade-calculator': { inputs:[{key:'v0',label:'Item score (%)',value:90,type:'number',min:0,max:100,step:.1,help:'Score earned on the assignment, test, or category.'},{key:'v1',label:'Item weight (%)',value:30,type:'number',min:0,max:100,step:.1,help:'How much this item counts toward the course grade.'},{key:'v2',label:'Current grade before item (%)',value:80,type:'number',min:0,max:100,step:.1,help:'Current average for the remaining coursework before adding this item.'}] },
  'final-exam-calculator': { inputs:[{key:'v0',label:'Current grade (%)',value:82,type:'number',min:0,max:100,step:.1,help:'Your current course grade before the final exam.'},{key:'v1',label:'Desired course grade (%)',value:85,type:'number',min:0,max:100,step:.1,help:'Target overall course grade.'},{key:'v2',label:'Final exam weight (%)',value:30,type:'number',min:.1,max:100,step:.1,help:'How much the final exam counts toward the course grade.'}] },
  'attendance-calculator': { inputs:[{key:'v0',label:'Classes attended',value:42,type:'number',min:0,max:100000,step:1,help:'Classes attended so far.'},{key:'v1',label:'Total classes held',value:48,type:'number',min:1,max:100000,step:1,help:'Total classes held so far.'},{key:'v2',label:'Required attendance threshold (%)',value:75,type:'number',min:0,max:100,step:.1,help:'Minimum attendance target to maintain or reach.'},{key:'v3',label:'Remaining classes',value:20,type:'number',min:0,max:100000,step:1,help:'Classes still scheduled in the planning period.'}] },
  'reading-time-calculator': { inputs:[{key:'v0',label:'Word count',value:1500,type:'number',min:0,max:10000000,step:1,help:'Total words in the article, essay, book, or script.'},{key:'v1',label:'Silent reading speed (WPM)',value:238,type:'number',min:1,max:2000,step:1,help:'Words per minute for your typical silent reading pace.'},{key:'v2',label:'Reading aloud speed (WPM)',value:150,type:'number',min:1,max:500,step:1,help:'Words per minute when reading aloud or presenting.'}] },
  'words-to-pages-calculator': { inputs:[{key:'v0',label:'Word count',value:2000,type:'number',min:0,max:10000000,step:1,help:'Total words in the essay, manuscript, article, or document.'},{key:'v1',label:'Words per page (selected format)',value:250,type:'number',min:1,max:2000,step:1,help:'Words that fit on one page in your font, spacing, margin, and page-size setup.'}] },
  'study-time-calculator': { inputs:[{key:'v0',label:'Courses enrolled',value:5,type:'number',min:1,max:30,step:1,help:'Number of courses in your current term.'},{key:'v1',label:'Credits per course',value:3,type:'number',min:.5,max:12,step:.5,help:'Typical credit value for each course.'},{key:'v2',label:'Study hours per credit per week',value:3,type:'number',min:1,max:8,step:.5,help:'Planning assumption; your institution or course may recommend a different workload.'},{key:'v3',label:'Weeks in term',value:15,type:'number',min:1,max:52,step:1,help:'Length of the study period or academic term.'}] },
  'force-calculator': { inputs:[{key:'v0',label:'Mass (kg)',value:10,type:'number',min:0,max:1000000,step:.01,help:'Mass in kilograms for the F = ma model.'},{key:'v1',label:'Acceleration (m/s²)',value:9.81,type:'number',min:0,max:1000000,step:.01,help:'Acceleration in meters per second squared.'}] },
  'kinetic-energy-calculator': { inputs:[{key:'v0',label:'Mass (kg)',value:10,type:'number',min:0,max:1000000,step:.01,help:'Mass of the moving object in kilograms.'},{key:'v1',label:'Velocity (m/s)',value:5,type:'number',min:0,max:1000000,step:.01,help:'Speed magnitude in meters per second.'}] },
  'inventory-turnover-calculator': { inputs:[{key:'v0',label:'Cost of goods sold (COGS)',value:120000,type:'number',min:.01,step:.01,help:'Direct costs of goods sold for the measurement period.'},{key:'v1',label:'Average inventory',value:20000,type:'number',min:.01,step:.01,help:'Average inventory value for the same measurement period.'}] },
};
for (const tool of core) if (validatedRemaining[tool.slug]) Object.assign(tool, validatedRemaining[tool.slug]);
const highIntentCopy: Record<string, string> = {
  'gpa-calculator': 'Calculate GPA from total quality points and credits on a 4.0, 5.0, or 10.0 grading scale, with transparent weighting and institution-specific caveats.',
  'grade-percentage-calculator': 'Calculate a test or assignment percentage from points earned and points possible, optionally adding curve or bonus points while keeping letter-grade cutoffs institution-specific.',
  'weighted-grade-calculator': 'Project a course grade from an item score, item weight, and current grade before the item, while showing weighted contribution and remaining weight.',
  'final-exam-calculator': 'Calculate the minimum final-exam score needed to reach a desired course grade from your current grade and final-exam weight, with feasibility and limitation checks.',
  'ohms-law-calculator': 'Solve Ohm’s law from any two common electrical values—voltage, current, resistance, or power—with derived results, formulas, and safe interpretation notes.',
  'simple-interest-calculator': 'Calculate simple interest, total amount, and interest earned or owed from principal, rate, and time.',
  'roi-calculator': 'Calculate standard ROI, investment gain or loss, and annualized ROI from initial cost, final value, and holding period.',
  'discount-calculator': 'Calculate the sale price, savings amount, and final total after a percentage discount.',
  'tip-calculator': 'Calculate a restaurant tip, total bill, and per-person split for any tip rate and group size.',
  'body-fat-calculator': 'Estimate body-fat percentage from BMI and age while exposing the screening equation and its limitations.',
  'ideal-weight-calculator': 'Estimate a height-based reference weight and explain why a healthy target is not one universal number.',
  'water-intake-calculator': 'Estimate a daily water target from body weight and exercise while keeping climate and medical variation visible.',
  'running-pace-calculator': 'Calculate pace, speed, and finish-time relationships from distance and elapsed time.',
  'heart-rate-zone-calculator': 'Estimate training heart-rate zones from age and target intensity using an explicit maximum-heart-rate model.',
  'average-calculator': 'Calculate the arithmetic mean from values, total, and count with transparent sum and item-count context.',
  'ratio-calculator': 'Reduce a ratio, compare its parts, and find equivalent proportions from two values.',
  'pythagorean-theorem-calculator': 'Find a missing side of a right triangle and verify the Pythagorean relationship.',
  'circle-area-calculator': 'Calculate circle area and show the relationship between radius, diameter, and circumference.',
  'triangle-area-calculator': 'Calculate triangle area from base and height with clear square-unit context.',
  'square-root-calculator': 'Find a square root and show the squared check for a non-negative number.',
  'add-days-calculator': 'Add or subtract calendar days from a start date and return the resulting date.',
  'business-days-calculator': 'Count weekdays between two dates while separating Monday–Friday counting from public holidays.',
  'time-duration-calculator': 'Calculate elapsed time between two clock times in hours, minutes, and seconds.',
  'countdown-calculator': 'Count the remaining time until a target date and make the boundary assumption visible.',
  'paint-calculator': 'Estimate paint quantity from surface area, coverage, coats, and purchasable container rounding.',
  'tile-calculator': 'Estimate tiles and boxes from area, tile size, and waste allowance.',
  'flooring-calculator': 'Estimate flooring area, waste allowance, and boxes or planks needed for a project.',
  'gravel-calculator': 'Estimate gravel volume and order quantity for driveways, paths, and landscaping beds.',
  'roof-pitch-calculator': 'Calculate roof slope, pitch ratio, angle, and the roof-surface multiplier from rise and run.',
  'brick-calculator': 'Estimate brick count from wall area and brick face area with practical rounding guidance.',
  'markup-calculator': 'Calculate markup, selling price, margin, and profit per unit from cost and pricing.',
  'break-even-calculator': 'Calculate break-even units, break-even sales revenue, contribution margin, and target-profit volume from fixed costs, price, and variable cost.',
  'cagr-calculator': 'Calculate compound annual growth rate (CAGR), annualized return, total growth, ending multiple, and absolute change from beginning value, ending value, and years.',
  'customer-acquisition-cost-calculator': 'Calculate customer acquisition cost (CAC) from total marketing and sales spend and new customers acquired in the same period, with efficiency context and attribution limitations.',
  'customer-lifetime-value-calculator': 'Estimate customer lifetime value (CLV/LTV) from average order value, purchase frequency, customer lifespan, and gross margin, while separating revenue CLV from profit-based CLV.',
  'conversion-rate-calculator': 'Calculate conversion rate from conversions and visitors, with non-converting visitors, visitors per conversion, and per-1,000 context while keeping the goal definition and measurement window explicit.',
  'inventory-turnover-calculator': 'Calculate inventory turnover, days inventory on hand, monthly turns, and inventory share from COGS and average inventory for the same period.',
  'attendance-calculator': 'Calculate attendance percentage, missed classes, classes needed to reach a required threshold, and how many remaining classes you can miss.',
  'reading-time-calculator': 'Estimate silent-reading and read-aloud time from word count and adjustable words-per-minute speeds, with slow and fast pace comparisons.',
  'words-to-pages-calculator': 'Estimate pages for an essay, manuscript, article, or document from word count and custom words-per-page density, with single- and double-spaced benchmarks.',
  'study-time-calculator': 'Plan weekly, daily, per-course, and total-term study time from courses, credits, study hours per credit, and term length while keeping the workload heuristic visible.',
  'force-calculator': 'Solve net force, mass, or acceleration using Newton’s second law, with inverse modes, SI-unit conversions, and explicit sign and model assumptions.',
  'kinetic-energy-calculator': 'Solve kinetic energy, mass, or velocity using KE = ½mv², with joule and kilojoule outputs and an explicit classical-model limitation.',
  'potential-energy-calculator': 'Calculate gravitational potential energy from mass, gravity, and height.',
  'electric-power-calculator': 'Calculate electrical power, energy per hour, and resistance from voltage and current.',
  'density-calculator': 'Calculate density, specific volume, and the relationship between mass and volume.',
  'molarity-calculator': 'Calculate solution molarity from moles and liters and show millimolar concentration.',
  'wave-speed-calculator': 'Calculate wave speed from frequency and wavelength and show the period relationship.',
};
const categoryCopy: Record<string, string> = {
  finance: 'Model the financial result with transparent inputs, formula, assumptions, and planning context.',
  health: 'Estimate the health metric for education and planning; it is not a diagnosis or individualized medical advice.',
  math: 'Solve the mathematical relationship and expose the formula, inputs, and result interpretation.',
  'date-time': 'Calculate the date or time relationship with explicit boundary and calendar assumptions.',
  construction: 'Estimate materials or dimensions with practical rounding, waste, and site-condition limitations.',
  business: 'Model the business metric with explicit inputs, scenario context, and assumptions.',
  education: 'Calculate the academic result with transparent weights, units, and institution-specific limitations.',
  science: 'Solve the scientific relationship with named variables, units, and significant-figure guidance.',
};
const coreSources: Record<string, { label: string; url: string }[]> = {
  'mortgage-calculator': [{ label: 'Fannie Mae mortgage calculator guidance', url: 'https://yourhome.fanniemae.com/calculators-resources/mortgage-calculator' }],
  'discount-calculator': [{ label: 'Calculator.net discount calculator reference', url: 'https://www.calculator.net/discount-calculator.html' }],
  'tip-calculator': [{ label: 'TipCalculator.org tipping guidance', url: 'https://tipcalculator.org/' }],
  'compound-interest-calculator': [{ label: 'Investor.gov compound interest calculator', url: 'https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator' }],
  'bmi-calculator': [{ label: 'CDC Adult BMI Calculator and categories', url: 'https://www.cdc.gov/bmi/adult-calculator/index.html' }],
  'bmr-calculator': [{ label: 'Mifflin–St Jeor resting-energy equation', url: 'https://pubmed.ncbi.nlm.nih.gov/2305711/' }],
  'tdee-calculator': [{ label: 'Mifflin–St Jeor resting-energy equation', url: 'https://pubmed.ncbi.nlm.nih.gov/2305711/' }],
  'body-fat-calculator': [{ label: 'Deurenberg adult body-fat equation review', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8980724/' }],
  'ideal-weight-calculator': [{ label: 'Calculator.net ideal weight formula reference', url: 'https://www.calculator.net/ideal-weight-calculator.html' }],
  'water-intake-calculator': [{ label: 'Bluevua daily water intake guidance', url: 'https://bluevua.com/pages/daily-water-intake-calculator' }],
  'running-pace-calculator': [{ label: 'CalculatorSoup pace calculator reference', url: 'https://www.calculatorsoup.com/calculators/health/pace-calculator.php' }],
  'heart-rate-zone-calculator': [{ label: 'McMillan Running heart-rate zone reference', url: 'https://www.mcmillanrunning.com/heart-rate-zone-calculator/' }],
  'paint-calculator': [{ label: 'Behr paint calculator guidance', url: 'https://www.behr.com/consumer/how-to/interior/paint-calculator' }],
  'percentage-calculator': [{ label: 'Pearson percentage formulas and examples', url: 'https://www.pearson.com/channels/calculators/percentage-calculator' }],
  'age-calculator': [{ label: 'Pearson exact age calculator reference', url: 'https://www.pearson.com/channels/calculators/age-calculator' }],
  'date-difference-calculator': [{ label: 'Timeanddate date-duration reference', url: 'https://www.timeanddate.com/date/duration.html' }],
  'square-footage-calculator': [{ label: 'Calculator.net area calculator reference', url: 'https://www.calculator.net/area-calculator.html' }],
  'tile-calculator': [{ label: 'Calculator.net tile calculator reference', url: 'https://www.calculator.net/tile-calculator.html' }],
  'flooring-calculator': [{ label: 'Flooring calculator and waste guidance', url: 'https://remodelcalculators.com/flooring-calculator' }],
  'gravel-calculator': [{ label: 'Gravel volume and compaction guidance', url: 'https://calcengineer.com/construction/gravel-calculator/' }],
  'roof-pitch-calculator': [{ label: 'Omni Calculator roof pitch reference', url: 'https://www.omnicalculator.com/construction/roof-pitch' }],
  'brick-calculator': [{ label: 'Glen-Gery brick calculator reference', url: 'https://www.glengery.com/brick-calculator' }],
  'concrete-calculator': [{ label: 'Concrete volume and waste guidance', url: 'https://concrete-calcs.com/' }],
  'profit-margin-calculator': [{ label: 'BDC net profit margin guidance', url: 'https://www.bdc.ca/en/articles-tools/entrepreneur-toolkit/financial-tools/net-profit-margin' }],
  'markup-calculator': [{ label: 'Sage markup formula guidance', url: 'https://www.sage.com/en-us/blog/markup-calculator/' }],
  'break-even-calculator': [{ label: 'Pearson break-even point formula', url: 'https://www.pearson.com/channels/calculators/break-even-point-calculator' }, { label: 'U.S. Small Business Administration break-even guidance', url: 'https://legacy.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point' }],
  'cagr-calculator': [{ label: 'Investopedia CAGR definition and formula', url: 'https://www.investopedia.com/terms/c/cagr.asp' }, { label: 'Wall Street Prep CAGR formula reference', url: 'https://www.wallstreetprep.com/knowledge/cagr-compound-annual-growth-rate/' }, { label: 'CalculatorSoup CAGR calculator reference', url: 'https://www.calculatorsoup.com/calculators/financial/cagr-calculator.php' }],
  'customer-acquisition-cost-calculator': [{ label: 'American Marketing Association CAC calculator guidance', url: 'https://www.ama.org/toolkits/ama-customer-acquisition-cost-calculator' }, { label: 'Zendesk customer acquisition cost formula', url: 'https://www.zendesk.com/blog/sales/sales-performance-metrics/customer-acquisition-cost/' }],
  'customer-lifetime-value-calculator': [{ label: 'Salesforce customer lifetime value formula guidance', url: 'https://www.salesforce.com/blog/sales/customer-lifetime-value' }, { label: 'Twilio CLV revenue and profit-margin formulas', url: 'https://www.twilio.com/en-us/blog/insights/customer-lifetime-value-clv' }],
  'conversion-rate-calculator': [{ label: 'Wall Street Prep conversion-rate formula reference', url: 'https://www.wallstreetprep.com/knowledge/conversion-rate/' }, { label: 'Kissmetrics conversion-rate examples and segmentation guidance', url: 'https://kissmetrics.io/blog/how-to-calculate-conversion-rate' }],
  'inventory-turnover-calculator': [{ label: 'BDC inventory turnover ratio calculator guidance', url: 'https://www.bdc.ca/en/articles-tools/entrepreneur-toolkit/financial-tools/inventory-turnover-benchmarking-tool' }, { label: 'NetSuite inventory turnover ratio formula', url: 'https://www.netsuite.com/portal/resource/articles/inventory-management/inventory-turnover-ratio.shtml' }],
  'gpa-calculator': [{ label: 'Pearson GPA scale and quality-points reference', url: 'https://www.pearson.com/channels/calculators/gpa-calculator' }],
  'grade-percentage-calculator': [{ label: 'Pearson test-grade formula and curve reference', url: 'https://www.pearson.com/channels/calculators/test-grade-calculator' }, { label: 'Juniata points-based grade calculator', url: 'https://www.juniata.edu/academics/quest/academic-resources/grade-calculator/pointsBasedCalc.html' }],
  'weighted-grade-calculator': [{ label: 'CalculatorSoup weighted grade formula', url: 'https://www.calculatorsoup.com/calculators/statistics/grade-calculator.php' }, { label: 'Pearson projected course-grade formula', url: 'https://www.pearson.com/channels/calculators/final-grade-calculator' }],
  'final-exam-calculator': [{ label: 'Pearson final-grade formula and projection guidance', url: 'https://www.pearson.com/channels/calculators/final-grade-calculator' }, { label: 'CalculatorSoup required final-grade formula', url: 'https://www.calculatorsoup.com/calculators/statistics/final-grade-calculator.php' }],
  'attendance-calculator': [{ label: 'OpenEduCat attendance formula guidance', url: 'https://www.openeducat.org/tools/attendance-calculator' }, { label: 'AttendanceCalc target and threshold guidance', url: 'https://attendancecalc.com/' }],
  'reading-time-calculator': [{ label: 'PRSA estimated reading-time formula guidance', url: 'https://www.prsa.org/article/how-to-determine-average-reading-time' }, { label: 'The Read Time reading-speed research context', url: 'https://thereadtime.com/' }],
  'words-to-pages-calculator': [{ label: 'WordCounter.ai words-per-page assumptions', url: 'https://wordcounter.ai/words-per-page/' }, { label: 'WordCounter.io 1,000-word page examples', url: 'https://wordcounter.io/faq/how-many-pages-is-1000-words' }],
  'study-time-calculator': [{ label: 'UW study-hours-per-credit guidance', url: 'https://uwex.wisconsin.edu/online-learning/time-management-calculator' }, { label: 'Penn State course-work workload guidance', url: 'https://student.worldcampus.psu.edu/course-work-and-success/preparing-and-attending-courses/time-management-calculator' }],
  'force-calculator': [{ label: 'CalculatorSoup F = ma reference and examples', url: 'https://www.calculatorsoup.com/calculators/physics/force.php' }, { label: 'Physics Fundamentals Newton’s second-law calculator', url: 'https://physicsfundamentals.org/calculators/newtons-second-law' }],
  'kinetic-energy-calculator': [{ label: 'CalculatorSoup kinetic-energy formula and inverse modes', url: 'https://www.calculatorsoup.com/calculators/physics/kinetic.php' }, { label: 'Georgia Tech kinetic-energy units and relativistic limitation', url: 'https://www.physicsbook.gatech.edu/Kinetic_Energy' }],
  'ohms-law-calculator': [{ label: "DigiKey Ohm's Law calculator reference", url: 'https://www.digikey.com/en/resources/conversion-calculators/conversion-calculator-ohms' }],
};
for (const tool of core) {
  const baseName = tool.title.replace(' Calculator', '').toLowerCase();
  const copy = highIntentCopy[tool.slug] || `${baseName[0].toUpperCase()}${baseName.slice(1)} calculator with visible formula, assumptions, and result context.`;
  if (!tool.advanced) tool.description = copy;
  if (tool.slug === 'ohms-law-calculator') tool.formula = 'Choose any two of V, I, R, or P; derive the missing value with Ohm’s law and the power relationships.';
  if (tool.slug === 'gpa-calculator') tool.formula = 'GPA = total quality points ÷ attempted credits; interpret the result on the selected institutional scale.';
  if (tool.slug === 'grade-percentage-calculator') { tool.formula = 'Raw percentage = points earned ÷ points possible × 100; adjusted percentage = (earned + curve) ÷ possible × 100'; tool.keywords = [...new Set([...tool.keywords, 'grade percentage calculator', 'test grade calculator', 'score percentage calculator', 'points earned percentage calculator', 'curve grade calculator', 'how to calculate test percentage'])]; }
  if (tool.slug === 'weighted-grade-calculator') { tool.formula = 'Projected course grade = current grade × (1 − item weight) + item score × item weight; weighted average = sum(score × weight) ÷ sum(weights)'; tool.keywords = [...new Set([...tool.keywords, 'weighted grade calculator', 'weighted average grade calculator', 'projected course grade calculator', 'grade contribution calculator', 'how to calculate weighted grade', 'assignment weight calculator'])]; }
  if (tool.slug === 'final-exam-calculator') { tool.formula = 'Required final = (desired grade − current grade × (1 − final weight)) ÷ final weight'; tool.keywords = [...new Set([...tool.keywords, 'final exam calculator', 'required final exam score calculator', 'what grade do I need on my final', 'final grade calculator', 'target course grade calculator', 'how to calculate final exam score'])]; }
  if (tool.slug === 'cagr-calculator') { tool.formula = 'CAGR = (ending value ÷ beginning value)^(1 ÷ years) − 1; total growth = ending ÷ beginning − 1'; tool.keywords = [...new Set([...tool.keywords, 'compound annual growth rate calculator', 'annualized return calculator', 'investment growth rate calculator', 'CAGR formula', 'how to calculate CAGR', 'future value with CAGR'])]; }
  if (tool.slug === 'customer-lifetime-value-calculator') { tool.formula = 'Revenue CLV = average order value × purchases per year × customer lifespan; profit CLV = revenue CLV × gross margin'; tool.keywords = [...new Set([...tool.keywords, 'customer lifetime value calculator', 'CLV calculator', 'LTV calculator', 'customer lifetime value formula', 'customer value calculator', 'how to calculate CLV', 'revenue versus profit CLV'])]; }
  if (tool.slug === 'conversion-rate-calculator') { tool.formula = 'Conversion rate = conversions ÷ visitors × 100; non-converting visitors = visitors − conversions'; tool.keywords = [...new Set([...tool.keywords, 'conversion rate calculator', 'website conversion rate calculator', 'conversion rate formula', 'conversion rate per 1000 visitors', 'how to calculate conversion rate', 'visitor to customer conversion rate'])]; }
  if (tool.slug === 'inventory-turnover-calculator') { tool.formula = 'Inventory turnover = COGS ÷ average inventory; days inventory = 365 ÷ inventory turnover'; tool.keywords = [...new Set([...tool.keywords, 'inventory turnover calculator', 'inventory turnover ratio calculator', 'days inventory calculator', 'inventory days on hand calculator', 'COGS divided by average inventory', 'how to calculate inventory turnover'])]; }
  if (tool.slug === 'attendance-calculator') { tool.formula = 'Attendance = attended ÷ total × 100; target planning uses total future classes and required threshold'; tool.keywords = [...new Set([...tool.keywords, 'attendance percentage calculator', 'attendance calculator 75 percent', 'how many classes can I miss', 'classes needed to reach attendance', 'attendance threshold calculator', 'attendance rate calculator'])]; }
  if (tool.slug === 'reading-time-calculator') { tool.formula = 'Reading time = word count ÷ words per minute; compare silent and read-aloud rates'; tool.keywords = [...new Set([...tool.keywords, 'reading time calculator', 'words to minutes', 'how long to read 1000 words', 'reading time by word count', 'average reading speed calculator', 'minutes per word calculator', 'reading aloud time calculator'])]; }
  if (tool.slug === 'words-to-pages-calculator') { tool.formula = 'Pages = word count ÷ words per page; compare with standard single- and double-spaced benchmarks'; tool.keywords = [...new Set([...tool.keywords, 'words to pages calculator', 'how many pages is 1000 words', 'words per page calculator', 'word count to pages', 'essay pages calculator', 'single spaced words per page', 'double spaced words per page'])]; }
  if (tool.slug === 'study-time-calculator') { tool.formula = 'Weekly study = courses × credits per course × study hours per credit; term total = weekly study × weeks'; tool.keywords = [...new Set([...tool.keywords, 'study time calculator', 'how many hours study per credit hour', 'weekly study hours calculator', 'college workload calculator', 'study hours per week', '3 hours per credit hour', 'student time management calculator'])]; }
  if (tool.slug === 'force-calculator') { tool.formula = 'Newton’s second law: F = m × a; inverse forms are m = F ÷ a and a = F ÷ m'; tool.keywords = [...new Set([...tool.keywords, 'force calculator', 'F ma calculator', 'Newton second law calculator', 'net force calculator', 'mass force acceleration calculator', 'how to calculate force', 'force equals mass times acceleration'])]; }
  if (tool.slug === 'kinetic-energy-calculator') { tool.formula = 'Kinetic energy: KE = ½ × m × v²; inverse forms are m = 2KE ÷ v² and v = √(2KE ÷ m)'; tool.keywords = [...new Set([...tool.keywords, 'kinetic energy calculator', 'KE calculator', 'kinetic energy formula', 'mass velocity energy calculator', 'how to calculate kinetic energy', 'kinetic energy in joules', 'kinetic energy from velocity'])]; }
  if (coreSources[tool.slug]) tool.sources = coreSources[tool.slug];
  const phrase = tool.slug.replace(/-calculator$/, '').replaceAll('-', ' ');
  tool.keywords = [...new Set([`${phrase} calculator`, `how to calculate ${phrase}`, `${phrase} formula`, `${tool.category} calculator`, ...tool.keywords])];
}

const groups = {
  Length: [['millimeter','mm',.001],['centimeter','cm',.01],['meter','m',1],['kilometer','km',1000],['inch','in',.0254],['foot','ft',.3048],['yard','yd',.9144],['mile','mi',1609.344],['nautical-mile','nmi',1852],['micrometer','µm',1e-6],['nanometer','nm',1e-9]],
  Mass: [['milligram','mg',1e-6],['gram','g',.001],['kilogram','kg',1],['metric-ton','t',1000],['ounce','oz',.028349523125],['pound','lb',.45359237],['stone','st',6.35029318],['us-ton','US ton',907.18474],['carat','ct',.0002]],
  Area: [['square-meter','m²',1],['square-kilometer','km²',1e6],['square-foot','ft²',.09290304],['square-inch','in²',.00064516],['square-yard','yd²',.83612736],['acre','acre',4046.8564224],['hectare','ha',10000],['square-mile','mi²',2589988.110336]],
  Volume: [['milliliter','mL',.001],['liter','L',1],['cubic-meter','m³',1000],['teaspoon','tsp',.00492892159375],['tablespoon','tbsp',.01478676478125],['cup','cup',.2365882365],['pint','pt',.473176473],['gallon','gal',3.785411784]],
  Speed: [['meter-per-second','m/s',1],['kilometer-per-hour','km/h',.2777777778],['mile-per-hour','mph',.44704],['foot-per-second','ft/s',.3048],['knot','kn',.514444],['mach','Mach',343],['speed-of-light','c',299792458]],
} as const;
const converters: Tool[] = [];
for (const [group, units] of Object.entries(groups)) for (const from of units) for (const to of units) if (from[0] !== to[0]) {
  const factor = Number(from[2]) / Number(to[2]);
  const inverse = 1 / factor;
  const fromName = String(from[0]).replaceAll('-', ' ');
  const toName = String(to[0]).replaceAll('-', ' ');
  converters.push({
    category: 'converters',
    group,
    slug: `${from[0]}-to-${to[0]}-converter`,
    title: `${from[1]} to ${to[1]} Converter`,
    description: `Convert ${from[1]} (${fromName}) to ${to[1]} (${toName}) using an exact ${group.toLowerCase()} conversion factor. See the forward and inverse factors, a worked 1-unit example, and practical precision guidance.`,
    op: 'convert',
    inputs: [{ key: 'v0', label: `${from[1]} value`, value: 1, type: 'number', min: 0, help: `Enter a value in ${from[1]} (${fromName}).` }],
    formula: `1 ${from[1]} = ${factor.toPrecision(10)} ${to[1]}; reverse: 1 ${to[1]} = ${inverse.toPrecision(10)} ${from[1]}`,
    unit: String(to[1]),
    params: [Number(from[2]), Number(to[2])],
    keywords: [`${from[1]} to ${to[1]} converter`, `${fromName} to ${toName} conversion`, `how many ${to[1]} in a ${from[1]}`, `${group.toLowerCase()} conversion`],
  });
}
export const tools=[...core,...converters];export const featured=tools.filter(tool=>tool.featured);export const byCategory=(category:string)=>tools.filter(tool=>tool.category===category);export const findTool=(category:string,slug:string)=>tools.find(tool=>tool.category===category&&tool.slug===slug);
