import type { Lang } from './site';

export type CollectionCopy={title:string;description:string;intro:string};
export type CalculatorCollection={slug:string;icon:string;toolKeys:string[];copy:Record<Lang,CollectionCopy>};
const copy=(en:CollectionCopy,de:CollectionCopy,fr:CollectionCopy,it:CollectionCopy,ja:CollectionCopy,es:CollectionCopy,pt:CollectionCopy):Record<Lang,CollectionCopy>=>({en,de,fr,it,ja,es,pt});
export const collections:CalculatorCollection[]=[
{slug:'student-tools',icon:'A+',toolKeys:['education/gpa-calculator','education/grade-percentage-calculator','education/weighted-grade-calculator','education/final-exam-calculator','education/attendance-calculator','education/reading-time-calculator','education/words-to-pages-calculator','education/study-time-calculator','math/percentage-calculator'],copy:copy(
{title:'Student calculator toolkit',description:'GPA, grades, attendance, study planning and reading calculators for students and teachers.',intro:'Plan coursework, understand grades and turn study goals into clear numbers with one focused toolkit.'},
{title:'Rechner für Schüler und Studierende',description:'GPA-, Noten-, Anwesenheits-, Lernzeit- und Leserechner für Lernende und Lehrkräfte.',intro:'Plane Kurse, verstehe Noten und verwandle Lernziele in klare Zahlen.'},
{title:'Outils de calcul pour étudiants',description:'Calculateurs de moyenne, notes, présence, révision et lecture pour élèves et enseignants.',intro:'Planifiez les cours, comprenez les notes et transformez les objectifs d’étude en chiffres clairs.'},
{title:'Strumenti di calcolo per studenti',description:'Calcolatori per GPA, voti, frequenza, studio e lettura per studenti e docenti.',intro:'Pianifica i corsi, comprendi i voti e trasforma gli obiettivi di studio in numeri chiari.'},
{title:'学生向け計算ツール集',description:'GPA、成績、出席率、学習時間、読書時間をまとめて計算できます。',intro:'授業計画や成績確認、学習目標の数値化に役立つツール集です。'},
{title:'Herramientas de cálculo para estudiantes',description:'Calculadoras de GPA, notas, asistencia, estudio y lectura para estudiantes y docentes.',intro:'Planifica cursos, entiende tus notas y convierte objetivos de estudio en cifras claras.'},
{title:'Ferramentas de cálculo para estudantes',description:'Calculadoras de GPA, notas, frequência, estudo e leitura para estudantes e professores.',intro:'Planeje disciplinas, entenda notas e transforme metas de estudo em números claros.'})},
{slug:'home-project-planning',icon:'◇',toolKeys:['construction/square-footage-calculator','construction/concrete-calculator','construction/tile-calculator','construction/flooring-calculator','construction/gravel-calculator','construction/paint-calculator','construction/brick-calculator','construction/roof-pitch-calculator'],copy:copy(
{title:'Home project planning calculators',description:'Estimate area, concrete, flooring, tile, gravel, paint, brick and roof pitch before buying materials.',intro:'Build a practical material estimate, compare assumptions and include waste before starting a home project.'},
{title:'Rechner für Heimprojekte',description:'Fläche, Beton, Boden, Fliesen, Kies, Farbe, Ziegel und Dachneigung vor dem Materialkauf schätzen.',intro:'Erstelle realistische Materialschätzungen und berücksichtige Verschnitt vor Projektbeginn.'},
{title:'Calculateurs pour projets maison',description:'Estimez surface, béton, sol, carrelage, gravier, peinture, briques et pente de toit.',intro:'Préparez une estimation pratique des matériaux et prévoyez les pertes avant les travaux.'},
{title:'Calcolatori per progetti domestici',description:'Stima area, cemento, pavimenti, piastrelle, ghiaia, vernice, mattoni e pendenza del tetto.',intro:'Prepara una stima pratica dei materiali e considera gli scarti prima dei lavori.'},
{title:'住宅プロジェクト計算ツール',description:'面積、コンクリート、床材、タイル、砂利、塗料、レンガ、屋根勾配を見積もります。',intro:'工事前に材料量、前提条件、廃材分をまとめて確認できます。'},
{title:'Calculadoras para proyectos del hogar',description:'Estima área, hormigón, pisos, baldosas, grava, pintura, ladrillos y pendiente del techo.',intro:'Prepara una estimación práctica de materiales e incluye desperdicio antes de comenzar.'},
{title:'Calculadoras para projetos domésticos',description:'Estime área, concreto, piso, azulejo, cascalho, tinta, tijolos e inclinação do telhado.',intro:'Monte uma estimativa prática de materiais e inclua perdas antes de começar.'})},
{slug:'small-business-metrics',icon:'▥',toolKeys:['business/profit-margin-calculator','business/break-even-calculator','business/markup-calculator','business/cagr-calculator','business/customer-acquisition-cost-calculator','business/customer-lifetime-value-calculator','business/conversion-rate-calculator','business/inventory-turnover-calculator'],copy:copy(
{title:'Small business metrics calculators',description:'Track margin, break-even, markup, growth, acquisition cost, lifetime value, conversion and inventory turnover.',intro:'Turn core operating figures into decision-ready business metrics with transparent formulas.'},
{title:'Kennzahlenrechner für kleine Unternehmen',description:'Marge, Break-even, Aufschlag, Wachstum, Akquisekosten, Kundenwert, Conversion und Lagerumschlag.',intro:'Verwandle operative Zahlen mit transparenten Formeln in entscheidungsreife Kennzahlen.'},
{title:'Calculateurs de gestion pour petites entreprises',description:'Marge, seuil de rentabilité, majoration, croissance, acquisition, valeur client, conversion et rotation.',intro:'Transformez les chiffres opérationnels en indicateurs utiles grâce à des formules transparentes.'},
{title:'Calcolatori per piccole imprese',description:'Margine, pareggio, ricarico, crescita, acquisizione, valore cliente, conversione e rotazione scorte.',intro:'Trasforma i dati operativi in metriche decisionali con formule trasparenti.'},
{title:'中小企業向け指標計算ツール',description:'利益率、損益分岐点、値入率、成長率、顧客獲得費用、顧客生涯価値、転換率、在庫回転率。',intro:'主要な事業数値を透明な計算式で意思決定に使える指標へ変換します。'},
{title:'Calculadoras de métricas para pequeñas empresas',description:'Margen, equilibrio, recargo, crecimiento, adquisición, valor del cliente, conversión e inventario.',intro:'Convierte cifras operativas en métricas listas para decidir con fórmulas transparentes.'},
{title:'Calculadoras de métricas para pequenas empresas',description:'Margem, equilíbrio, markup, crescimento, aquisição, valor do cliente, conversão e estoque.',intro:'Transforme números operacionais em métricas para decisões com fórmulas transparentes.'})},
{slug:'loan-and-savings-planning',icon:'↗',toolKeys:['finance/mortgage-calculator','finance/loan-calculator','finance/compound-interest-calculator','finance/savings-goal-calculator'],copy:copy(
{title:'Loan and savings planning calculators',description:'Compare mortgage and loan costs, compound growth and the monthly saving needed for a target.',intro:'Use consistent assumptions to compare borrowing, payoff and savings scenarios before making a financial decision.'},
{title:'Kredit- und Sparplanungsrechner',description:'Vergleiche Hypotheken- und Kreditkosten, Zinswachstum und monatliche Sparziele.',intro:'Vergleiche Kredit-, Tilgungs- und Sparszenarien mit einheitlichen Annahmen.'},
{title:'Calculateurs de prêt et d’épargne',description:'Comparez prêts, hypothèques, intérêts composés et épargne mensuelle nécessaire.',intro:'Comparez emprunt, remboursement et épargne avec des hypothèses cohérentes.'},
{title:'Calcolatori per prestiti e risparmio',description:'Confronta mutui, prestiti, crescita composta e risparmio mensile necessario.',intro:'Confronta scenari di prestito, rimborso e risparmio con ipotesi coerenti.'},
{title:'ローン・貯蓄計画ツール',description:'住宅ローン、各種ローン、複利成長、目標達成に必要な毎月の貯蓄額を比較します。',intro:'同じ前提条件で借入、返済、貯蓄のシナリオを比較できます。'},
{title:'Calculadoras para préstamos y ahorro',description:'Compara hipotecas, préstamos, crecimiento compuesto y ahorro mensual necesario.',intro:'Compara escenarios de deuda, pago y ahorro con supuestos coherentes.'},
{title:'Calculadoras para empréstimos e poupança',description:'Compare hipotecas, empréstimos, juros compostos e a poupança mensal necessária.',intro:'Compare cenários de dívida, pagamento e poupança com premissas consistentes.'})}
];
export const findCollection=(slug:string)=>collections.find(item=>item.slug===slug);
