export const SITE={name:'CalcWise',domain:'https://tool-website-ayu.pages.dev',email:'hello@example.com',adsenseClient:'',enableAds:false};
export const locales=['en','de','fr','it','ja','es','pt'] as const; export type Lang=typeof locales[number];
export const localeNames:Record<Lang,string>={en:'English',de:'Deutsch',fr:'Français',it:'Italiano',ja:'日本語',es:'Español',pt:'Português'};
export const ui={
en:{tag:'Answers without the busywork',hero:'Calculate anything. Understand everything.',sub:'400 free calculators, organized by category and built to show the method—not just the answer.',search:'Search calculators',popular:'Popular calculators',categories:'Browse by category',all:'All tools',formula:'Formula and method',example:'How to use it',related:'Related calculators',home:'Home',tools:'tools',result:'Result',privacy:'Your inputs stay in your browser.',language:'Language'},
de:{tag:'Antworten ohne Umwege',hero:'Alles berechnen. Alles verstehen.',sub:'400 kostenlose Rechner, nach Kategorien geordnet und mit nachvollziehbaren Formeln.',search:'Rechner suchen',popular:'Beliebte Rechner',categories:'Nach Kategorie',all:'Alle Tools',formula:'Formel und Methode',example:'Anwendung',related:'Ähnliche Rechner',home:'Start',tools:'Tools',result:'Ergebnis',privacy:'Ihre Eingaben bleiben im Browser.',language:'Sprache'},
fr:{tag:'Des réponses sans détour',hero:'Calculez tout. Comprenez tout.',sub:'400 calculateurs gratuits, classés par catégorie avec des formules transparentes.',search:'Rechercher',popular:'Calculateurs populaires',categories:'Par catégorie',all:'Tous les outils',formula:'Formule et méthode',example:'Mode d’emploi',related:'Outils associés',home:'Accueil',tools:'outils',result:'Résultat',privacy:'Vos données restent dans le navigateur.',language:'Langue'},
it:{tag:'Risposte senza complicazioni',hero:'Calcola tutto. Comprendi tutto.',sub:'400 calcolatori gratuiti, organizzati per categoria e con formule trasparenti.',search:'Cerca calcolatori',popular:'Calcolatori popolari',categories:'Sfoglia per categoria',all:'Tutti gli strumenti',formula:'Formula e metodo',example:'Come si usa',related:'Calcolatori correlati',home:'Home',tools:'strumenti',result:'Risultato',privacy:'I dati restano nel browser.',language:'Lingua'},
ja:{tag:'手間なく答えを',hero:'何でも計算。仕組みも理解。',sub:'カテゴリ別に整理された400個の無料計算ツール。数式と計算方法も表示します。',search:'計算ツールを検索',popular:'人気の計算ツール',categories:'カテゴリから探す',all:'すべてのツール',formula:'数式と計算方法',example:'使い方',related:'関連ツール',home:'ホーム',tools:'ツール',result:'結果',privacy:'入力内容はブラウザ内に保存されます。',language:'言語'},
es:{tag:'Respuestas sin complicaciones',hero:'Calcula todo. Entiende todo.',sub:'400 calculadoras gratis, organizadas por categoría y con fórmulas transparentes.',search:'Buscar calculadoras',popular:'Calculadoras populares',categories:'Explorar por categoría',all:'Todas las herramientas',formula:'Fórmula y método',example:'Cómo usarla',related:'Calculadoras relacionadas',home:'Inicio',tools:'herramientas',result:'Resultado',privacy:'Tus datos permanecen en el navegador.',language:'Idioma'},
pt:{tag:'Respostas sem complicação',hero:'Calcule tudo. Entenda tudo.',sub:'400 calculadoras grátis, organizadas por categoria e com fórmulas transparentes.',search:'Buscar calculadoras',popular:'Calculadoras populares',categories:'Explorar por categoria',all:'Todas as ferramentas',formula:'Fórmula e método',example:'Como usar',related:'Calculadoras relacionadas',home:'Início',tools:'ferramentas',result:'Resultado',privacy:'Seus dados ficam no navegador.',language:'Idioma'}} as const;
export const categories={finance:{en:'Finance',de:'Finanzen',fr:'Finance',it:'Finanza',ja:'金融',es:'Finanzas',pt:'Finanças',icon:'↗',color:'#1d7557'},health:{en:'Health',de:'Gesundheit',fr:'Santé',it:'Salute',ja:'健康',es:'Salud',pt:'Saúde',icon:'♥',color:'#c73d6f'},math:{en:'Math',de:'Mathematik',fr:'Maths',it:'Matematica',ja:'数学',es:'Matemáticas',pt:'Matemática',icon:'∑',color:'#7653c8'},'date-time':{en:'Date & time',de:'Datum & Zeit',fr:'Date et heure',it:'Data e ora',ja:'日時',es:'Fecha y hora',pt:'Data e hora',icon:'◷',color:'#2879bd'},construction:{en:'Construction',de:'Bauwesen',fr:'Construction',it:'Edilizia',ja:'建設',es:'Construcción',pt:'Construção',icon:'◇',color:'#ba6c20'},business:{en:'Business',de:'Unternehmen',fr:'Entreprise',it:'Business',ja:'ビジネス',es:'Negocios',pt:'Negócios',icon:'▥',color:'#397586'},education:{en:'Education',de:'Bildung',fr:'Éducation',it:'Istruzione',ja:'教育',es:'Educación',pt:'Educação',icon:'A+',color:'#9b6e13'},science:{en:'Science',de:'Wissenschaft',fr:'Sciences',it:'Scienza',ja:'科学',es:'Ciencia',pt:'Ciência',icon:'⚛',color:'#39766b'},converters:{en:'Unit converters',de:'Einheitenumrechner',fr:'Convertisseurs',it:'Convertitori',ja:'単位変換',es:'Convertidores',pt:'Conversores',icon:'⇄',color:'#8a5b3d'}} as const;
export type Category=keyof typeof categories;
export const path=(lang:Lang,rest='')=>`/${lang}/${rest}`.replace(/\/+/g,'/').replace(/([^/])$/,'$1/');
